/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-snd_framewok
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SND_FRAMEWOK_API_H
#define INCLUDED_SND_FRAMEWOK_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_snd_framewok_EXPORTS
#define SND_FRAMEWOK_API __GR_ATTR_EXPORT
#else
#define SND_FRAMEWOK_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SND_FRAMEWOK_API_H */
